// submarine-workbench/workbench-web-ng/src/app/pages/workbench/environment/environment.component.ts
/*!
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

import { Component, OnInit } from '@angular/core';
import { EnvironmentService } from '@submarine/services/environment.service';
import { Environment } from '@submarine/interfaces/environment-info';

@Component({
  selector: 'submarine-environment',
  templateUrl: './environment.component.html',
  styleUrls: ['./environment.component.scss']
})
export class EnvironmentComponent implements OnInit {
  constructor(private environmentService: EnvironmentService) {}

  environmentList: Environment[] = [];
  checkedList: boolean[] = [];
  selectAllChecked: boolean = false;

  ngOnInit() {
    this.fetchEnvironmentList();
  }

  fetchEnvironmentList() {
    this.environmentService.fetchEnvironmentList().subscribe((list) => {
      this.environmentList = list;
      this.checkedList = [];
      for (let i = 0; i < this.environmentList.length; i++) {
        this.checkedList.push(false);
      }
    });
  }

  // TODO(kobe860219): Create new environment
  createEnvironment(data) {}

  // TODO(kobe860219): Update an environment
  updateEnvironment(id: string, data) {}

  // TODO(kobe860219): Delete environment
  deleteEnvironment(id: string) {}

  selectAllEnv() {
    for (let i = 0; i < this.checkedList.length; i++) {
      this.checkedList[i] = this.selectAllChecked;
    }
  }
}

<!--
  ~ Licensed to the Apache Software Foundation (ASF) under one
  ~ or more contributor license agreements.  See the NOTICE file
  ~ distributed with this work for additional information
  ~ regarding copyright ownership.  The ASF licenses this file
  ~ to you under the Apache License, Version 2.0 (the
  ~ "License"); you may not use this file except in compliance
  ~ with the License.  You may obtain a copy of the License at
  ~
  ~   http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing,
  ~ software distributed under the License is distributed on an
  ~ "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  ~ KIND, either express or implied.  See the License for the
  ~ specific language governing permissions and limitations
  ~ under the License.
  -->

<nz-layout style="margin: -24px -24px 16px;">
  <nz-layout class="inner-layout">
    <div id="environmentOuter">
      <nz-breadcrumb>
        <nz-breadcrumb-item>
          <a [routerLink]="['/', 'workbench', 'home']">Home</a>
        </nz-breadcrumb-item>
        <nz-breadcrumb-item>
          <a [routerLink]="['/', 'workbench', 'environment']">environment</a>
        </nz-breadcrumb-item>
      </nz-breadcrumb>
      <div>
        <br />
        <h2>Environment</h2>
        <nz-content>
          Environment profiles defines a set of libraries and when Docker is being used, a Docker image in order to run
          an experiment or a notebook.
        </nz-content>
      </div>
      <br />
    </div>
  </nz-layout>
  <div id="environmentData">
    <div>
      <div align="right">
        <nz-input-group
          nzSearch
          style="width: 300px; margin-top: 15px; margin-left: 10px; margin-right: 5px;"
          [nzAddOnAfter]="suffixIconButton"
        >
          <input type="text" nz-input placeholder="input search text" />
        </nz-input-group>
        <ng-template #suffixIconButton>
          <button nz-button nzType="primary" nzSearch><i nz-icon nzType="search"></i></button>
        </ng-template>

        <button
          nz-button
          id="createEnvironment"
          nzType="primary"
          style="margin-right: 5px; margin-bottom: 15px; margin-top: 15px;"
        >
          <i nz-icon nzType="plus"></i>
          New Environment
        </button>
        <button
          nz-button
          id="deleteEnvironment"
          nzType="primary"
          style="margin-bottom: 15px; margin-top: 15px;"
          nz-popconfirm
          nzTitle="Confirm to delete?"
          nzCancelText="Cancel"
          nzOkText="Ok"
          (nzOnConfirm)="deleteEnvironment()"
        >
          <i nz-icon nzType="delete" nzTheme="outline"></i>
          Delete
        </button>
      </div>
      <nz-table id="releaseTable" nzBordered #basicTable [nzData]="environmentList" [nzNoResult]="'No data'">
        <thead>
          <tr>
            <th>
              <label nz-checkbox [(ngModel)]="selectAllChecked" (ngModelChange)="selectAllEnv()"></label>
            </th>
            <th>Environment Name</th>
            <th>Environment ID</th>
            <th>Docker image</th>
            <th>Kernel name</th>
            <th>Kernel channel</th>
            <th>Kernel dependencies</th>
          </tr>
        </thead>
        <tbody>
          <tr *ngFor="let data of basicTable.data; let i = index">
            <td>
              <label nz-checkbox [(ngModel)]="checkedList[i]"></label>
            </td>
            <td>{{ data.environmentSpec.name }}</td>
            <td>{{ data.environmentId }}</td>
            <td>{{ data.environmentSpec.dockerImage }}</td>
            <td>{{ data.environmentSpec.kernelSpec.name }}</td>
            <td>
              <dl *ngFor="let channel of data.environmentSpec.kernelSpec.channels">
                <dt>{{ channel }}</dt>
              </dl>
            </td>
            <td>
              <dl *ngFor="let dependency of data.environmentSpec.kernelSpec.dependencies">
                <dt>{{ dependency }}</dt>
              </dl>
            </td>
          </tr>
        </tbody>
      </nz-table>
    </div>
    <router-outlet></router-outlet>
  </div>
</nz-layout>

// submarine-workbench-v2/src/pages/workbench/environment/Environment.tsx
/*!
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

import { Layout } from "antd";

const { Content } = Layout;

function Environment() {
  return (
    <Layout data-testid="environment-page">
      <Content>Environment</Content>
    </Layout>
  );
}
export default Environment;
