// java/submarine-workbench/workbench-web/src/views/workbench/job/Job.vue
<!--
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-->
<template>
  <a-card :bordered="false">

    <div slot="extra">
      <a-radio-group>
        <a-radio-button>All</a-radio-button>
        <a-radio-button>Owned By Me</a-radio-button>
        <a-radio-button>Accessible By Me</a-radio-button>
      </a-radio-group>
      <a-input-search style="margin-left: 16px; width: 272px;" />
      <a-button style="margin-left: 8px" type="primary" icon="plus" @click="$refs.modal.edit(null)">New Job</a-button>
    </div>

    <s-table
      ref="table"
      size="default"
      :columns="columns"
      :data="loadData"
    >
      <span slot="serial" slot-scope="text, record, index">
        {{ index + 1 }}
      </span>
      <span slot="status" slot-scope="text">
        <a-badge :status="text | statusTypeFilter" :text="text | statusFilter" />
      </span>
      <span slot="description" slot-scope="text">
        <ellipsis :length="20" tooltip>{{ text }}</ellipsis>
      </span>

      <span slot="progressRender" slot-scope="text, record">
        <div class="list-content-item">
          <a-progress :percent="record.progress.value" :status="!record.progress.status ? null : record.progress.status" style="width: 180px" />
        </div>
      </span>

      <span slot="action" slot-scope="text, record">
        <template>
          <a @click="handleEdit(record)">Start</a>
          <a-divider type="vertical" />
          <a @click="handleSub(record)">Edit</a>
        </template>
      </span>
    </s-table>
    <create-form ref="createModal" @ok="handleOk" />
    <create-job-modal ref="modal" @ok="handleOk"/>
  </a-card>
</template>

<script>
import moment from 'moment'
import { STable, Ellipsis } from '@/components'
import CreateJobModal from '@/views/workbench/job/modules/CreateJob'
import { getRoleList } from '@/api/manage'
import { getJobList } from '@/api/workbench'

const statusMap = {
  0: {
    status: 'default',
    text: 'Stop'
  },
  1: {
    status: 'processing',
    text: 'Running'
  },
  2: {
    status: 'success',
    text: 'Online'
  },
  3: {
    status: 'error',
    text: 'Exception'
  }
}

export default {
  name: 'TableList',
  components: {
    STable,
    Ellipsis,
    CreateJobModal
  },
  data () {
    return {
      description: 'A job is a way of running a notebook or on a scheduled basis.',
      logo: 'https://gw.alipayobjects.com/zos/rmsportal/nxkuOJlFJuAUhzlMTCEe.png',
      mdl: {},
      // 高级搜索 展开/关闭
      advanced: false,
      // 查询参数
      queryParam: {},
      // 表头
      columns: [
        {
          title: 'Job Name',
          dataIndex: 'no'
        },
        {
          title: 'Job ID',
          dataIndex: 'id'
        },
        {
          title: 'Owner',
          dataIndex: 'owner',
          scopedSlots: { customRender: 'description' }
        },
        {
          title: 'Actuator',
          dataIndex: 'actuator',
          scopedSlots: { customRender: 'description' }
        },
        {
          title: 'Status',
          dataIndex: 'status',
          scopedSlots: { customRender: 'status' }
        },
        {
          title: 'Progress',
          dataIndex: 'progress',
          scopedSlots: { customRender: 'progressRender' }
        },
        {
          title: 'Last Run',
          dataIndex: 'updatedAt'
        },
        {
          title: 'Action',
          dataIndex: 'action',
          width: '250px',
          scopedSlots: { customRender: 'action' }
        }
      ],
      // 加载数据方法 必须为 Promise 对象
      loadData: parameter => {
        console.log('loadData.parameter', parameter)
        return getJobList(Object.assign(parameter, this.queryParam))
          .then(res => {
            return res.result
          })
      },
      selectedRowKeys: [],
      selectedRows: [],

      // custom table alert & rowSelection
      options: {
        alert: { show: true, clear: () => { this.selectedRowKeys = [] } },
        rowSelection: {
          selectedRowKeys: this.selectedRowKeys,
          onChange: this.onSelectChange
        }
      },
      optionAlertShow: false
    }
  },
  filters: {
    statusFilter (type) {
      return statusMap[type].text
    },
    statusTypeFilter (type) {
      return statusMap[type].status
    }
  },
  created () {
    getRoleList({ t: new Date() })
  },
  methods: {
    handleEdit (record) {
      console.log(record)
      this.$refs.modal.edit(record)
    },
    handleSub (record) {
      if (record.status !== 0) {
        this.$message.info(`${record.no} 订阅成功`)
      } else {
        this.$message.error(`${record.no} 订阅失败，规则已关闭`)
      }
    },
    handleOk () {
      this.$refs.table.refresh()
    },
    onSelectChange (selectedRowKeys, selectedRows) {
      this.selectedRowKeys = selectedRowKeys
      this.selectedRows = selectedRows
    },
    toggleAdvanced () {
      this.advanced = !this.advanced
    },
    resetSearchForm () {
      this.queryParam = {
        date: moment(new Date())
      }
    }
  }
}
</script>

// submarine-workbench/workbench-web-ng/src/app/pages/workbench/job/job.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'submarine-job',
  templateUrl: './job.component.html',
  styleUrls: ['./job.component.scss']
})
export class JobComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

}

<!--
  ~ Licensed to the Apache Software Foundation (ASF) under one
  ~ or more contributor license agreements.  See the NOTICE file
  ~ distributed with this work for additional information
  ~ regarding copyright ownership.  The ASF licenses this file
  ~ to you under the Apache License, Version 2.0 (the
  ~ "License"); you may not use this file except in compliance
  ~ with the License.  You may obtain a copy of the License at
  ~
  ~   http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing,
  ~ software distributed under the License is distributed on an
  ~ "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  ~ KIND, either express or implied.  See the License for the
  ~ specific language governing permissions and limitations
  ~ under the License.
  -->

<nz-layout style="margin: -24px -24px 16px;">
  <nz-layout class="inner-layout">
    <div id="jobOuter">
      <nz-breadcrumb>
        <nz-breadcrumb-item>
          <a [routerLink]="['/', 'workbench', 'home']">Home</a>
        </nz-breadcrumb-item>
        <nz-breadcrumb-item>Job</nz-breadcrumb-item>
      </nz-breadcrumb>
      <br/>
      <h2>Job</h2>
      <nz-content>A job is a way of running a notebook or on a scheduled basis.</nz-content>
      <br/>
    </div>
  </nz-layout>
  <div id="jobData">
    <div align="right">
      <nz-radio-group [(ngModel)]="showJob" (ngModelChange)="showChange()">
        <label nz-radio-button nzValue="All">All</label>
        <label nz-radio-button nzValue="Own">Owned By Me</label>
        <label nz-radio-button
               nzValue="Access">Accessable By Me</label>
      </nz-radio-group>
      <nz-input-group nzSearch
                      style="width:300px;margin-top: 15px;margin-left:10px;margin-right:5px;"
                      [nzAddOnAfter]="suffixIconButton">
        <input type="text"
               nz-input
               placeholder="input search text"/>
      </nz-input-group>
      <ng-template #suffixIconButton>
        <button nz-button
                nzType="primary"
                nzSearch><i nz-icon
                            nzType="search"></i></button>
      </ng-template>

      <button nz-button
              id="openJob"
              nzType="primary"
              style="margin-right: 30px;margin-bottom: 15px;margin-top: 15px;"
              (click)="isVisible=true;"><i nz-icon
                                           nzType="plus"></i>New Job
      </button>
    </div>
    <nz-table id="releaseTable" nzBordered #basicTable [nzData]="joblist" [nzNoResult]="'No data'">
      <thead>
        <tr>
          <th nzWidth="60px">Job Name</th>
          <th nzWidth="20px">Job ID</th>
          <th nzWidth="40px">Owner</th>
          <th nzWidth="60px">Actuator</th>
          <th nzWidth="60px">Status</th>
          <th nzWidth="60px">Progress</th>
          <th nzWidth="60px">Last Run</th>
          <th nzWidth="60px">Action</th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let data of basicTable.data">
          <td>{{ data.name }}</td>
          <td>{{ data.id }}</td>
          <td>{{ data.owner }}</td>
          <td>{{ data.actuator }}</td>
          <td>{{ data.status }}</td>
          <td><nz-progress nzStrokeLinecap="round" [nzPercent]="data.progress"></nz-progress></td>
          <td>{{ data.lastRun }}</td>
          <td><button nz-button nzType="link" (click)="startJob(data)" style="padding-left: 2px;padding-right: 5px;">Start</button>|<button nz-button nzType="link" (click)="editJob(data)" style="padding-left: 2px;padding-right: 5px;">Edit</button></td>
        </tr>
      </tbody>
    </nz-table>
  </div>
  <nz-modal
      [(nzVisible)]="isVisible"
      nzTitle="Create Job"
      [nzOkLoading]="isOkLoading"
      (nzOnCancel)="isVisible=false;"
      [nzWidth]="740"
  >
    <div >
      <nz-steps [nzCurrent]="current">
        <nz-step nzTitle="Basic Information"></nz-step>
        <nz-step nzTitle="Configuration"></nz-step>
        <nz-step nzTitle="Scheduling Cycle"></nz-step>
      </nz-steps>
    </div>
    <div>
      <form [formGroup]="createJob">
        <div *nzModalFooter>
          <button nz-button nzType="default" (click)="isVisible=false;"> Cancel </button>
          <button id="go" nz-button nzType="primary" [disabled]="!(createJob.get('jobName').valid && createJob.get('description').valid)" (click)="handleOk()">{{okText}}</button>
          <button *ngIf="current>0" nz-button nzType="default" style="float: left;" (click)="current=current-1;okText = 'Next Step';">Prev Step</button>
        </div>
        <div [ngSwitch]="current" style="margin-top: 30px;">
          <div *ngSwitchCase="0">
            <div>
              <label class="form-label"><span class="red-star">* </span> Job Name:</label>
              <input type="text" id="jobname" style="margin-top: 32px;width: 350px;" class="form-control" formControlName="jobName">
            </div>
            <div>
              <label class="form-label"><span class="red-star">* </span>Description:</label>
              <textarea rows="6" class="form-control" style="margin-top: 32px;width: 350px;" formControlName="description"></textarea>
            </div>
          </div>
          <div *ngSwitchCase="1" id="page2">
            <div>
              <label class="form-label"><span class="red-star">* </span> Monitor Object:</label>
              <nz-select formControlName="monitorObject" nzPlaceHolder="Choose" style="width: 350px;margin-top: 30px;">
                <nz-option *ngFor="let monitorObject of monitorObjects" [nzValue]="monitorObject" [nzLabel]="monitorObject"></nz-option>
              </nz-select>
            </div>
            <div>
              <label class="form-label"><span class="red-star">* </span> Rule Template:</label>
              <nz-select formControlName="ruleTemplate" nzPlaceHolder="Choose" style="width: 350px;margin-top: 30px;">
                <nz-option *ngFor="let ruleTemplate of ruleTemplates" [nzValue]="ruleTemplate" [nzLabel]="ruleTemplate"></nz-option>
              </nz-select>
            </div>
            <div>
              <label class="form-label"><span class="red-star">* </span> Rule Type:</label>
              <nz-radio-group formControlName="ruleType" style="width: 350px;margin-top: 30px;margin-bottom: 30px;">
                <label *ngFor="let ruletype of ruleTypes" nz-radio [nzValue]="ruletype">{{ ruletype }}</label>
              </nz-radio-group>
            </div>
          </div>
          <div *ngSwitchCase="2">
            <div>
              <label class="pg3-form-label"><span class="red-star">* </span> Start Date:</label>
              <nz-date-picker [nzFormat]="'yyyy/MM/dd'" formControlName="startDate" style="width: 350px;margin-top: 30px;"></nz-date-picker>
            </div>
            <div>
              <label class="pg3-form-label"><span class="red-star">* </span> Schedule Cycle:</label>
              <nz-select formControlName="scheduleCycle" nzPlaceHolder="Choose" style="width: 195px;margin-top: 30px;margin-bottom: 30px;">
                <nz-option *ngFor="let scheduleCycle of scheduleCycles" [nzValue]="scheduleCycle" [nzLabel]="scheduleCycle"></nz-option>
              </nz-select>
            </div>
          </div>
        </div>
      </form>
    </div>
  </nz-modal>
</nz-layout>
