// submarine-workbench/workbench-web-ng/src/app/pages/workbench/workspace/project/project.component.ts
/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

import { Component, OnInit, ViewChild, ElementRef } from '@angular/core';

@Component({
  selector: 'app-project',
  templateUrl: './project.component.html',
  styleUrls: ['./project.component.scss']
})
export class ProjectComponent implements OnInit {
  newProject = false;
  existProjects = [];

  @ViewChild('inputElement', { static: false }) inputElement: ElementRef;

  constructor() { }

  //Todo : get projects data from server
  ngOnInit() {
    this.existProjects.push({
      projectName: 'projectName0', description: 'description', tags: ['12', 'Tag 2'], inputTagVisibility: false, projectInputTag: ''
    });
    this.existProjects.push({
      projectName: 'projectName1', description: 'description', tags: ['Unremovable', 'Tag 2'], inputTagVisibility: false, projectInputTag: ''
    });
    this.existProjects.push({
      projectName: 'projectName1', description: 'description', tags: ['Unremovable', 'Tag 2', 'Tag 3'], inputTagVisibility: false, projectInputTag: ''
    });
    this.existProjects.push({
      projectName: 'projectName1', description: 'description', tags: ['Unremovable', 'Tag 2', 'Tag 3'], inputTagVisibility: false, projectInputTag: ''
    })
  }
  //Todo: Update tag in server
  handleCloseTag(project, tag){
    project.tags = project.tags.filter(itag => itag!==tag);
    console.log(project);
    console.log(tag);
  }
  //Todo update tag in server
  handleInputConfirm(project): void {
    if (project.projectInputTag && project.tags.indexOf(project.projectInputTag) === -1) {
      project.tags = [...project.tags, project.projectInputTag];
    }
    project.inputTagVisibility = false;
    project.projectInputTag = '';
  }

  showInput(project): void {
    project.inputTagVisibility = true;
    setTimeout(() => {
      this.inputElement.nativeElement.focus();
    }, 10);
  }


}

<!--
  ~ Licensed to the Apache Software Foundation (ASF) under one
  ~ or more contributor license agreements.  See the NOTICE file
  ~ distributed with this work for additional information
  ~ regarding copyright ownership.  The ASF licenses this file
  ~ to you under the Apache License, Version 2.0 (the
  ~ "License"); you may not use this file except in compliance
  ~ with the License.  You may obtain a copy of the License at
  ~
  ~   http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing,
  ~ software distributed under the License is distributed on an
  ~ "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  ~ KIND, either express or implied.  See the License for the
  ~ specific language governing permissions and limitations
  ~ under the License.
  -->

<br>
<nz-spin *ngIf="!newProject && isLoading" style="height: 50px;">
</nz-spin>
<div *ngIf="!newProject && !isLoading">
    <div id="addProjectbtn">
        <button nz-button nzBlock (click)="newProject=true">+ Add New Project</button>
    </div>
    <div id="projectTagDiv">
        <div nz-row [nzGutter]="12" nzType="flex" nzJustify="start">
          <div *ngFor="let project of existProjects" nz-col [nzSpan]="8" id="projectDiv">
            <nz-card [nzTitle]="project.projectName" [nzActions]="[actionEdit, actionDownload, actionSetting, actionDelete]">
                <nz-tag *ngFor="let tag of project.tags" [nzMode]="'closeable'" (nzAfterClose)="handleCloseTag(project, tag)">{{ tag }}</nz-tag>
                <nz-tag *ngIf="!project.inputTagVisibility" class="editable-tag" nzNoAnimation (click)="showInput(project)">
                    <i nz-icon nzType="plus"></i> New Tag
                </nz-tag>
                <input
                    #inputElement
                    nz-input
                    nzSize="small"
                    *ngIf="project.inputTagVisibility"
                    type="text"
                    [(ngModel)]="project.projectInputTag"
                    id="projectInputTag"
                    (blur)="handleInputConfirm(project)"
                    (keydown.enter)="handleInputConfirm(project)"
                    />
                <div>
                    <br>
                    {{ project.description}}
                    <br>
                    <br>
                    <label>
                        <i nz-icon nzType="star" nzTheme="outline"></i> &nbsp;{{ project.starNum }} &nbsp; | &nbsp;
                        <i nz-icon nzType="like" nzTheme="outline"></i> &nbsp; {{ project.likeNum }} &nbsp; | &nbsp;
                        <i nz-icon nzType="message" nzTheme="outline"></i> &nbsp; {{ project.msgNum }}
                    </label>
                </div>

                <ng-template #actionEdit>
                    <i nz-icon nzType="edit"></i>Edit
                </ng-template>
                <ng-template #actionDownload>
                    <i nz-icon nzType="download"></i>Download
                </ng-template>
                <ng-template #actionSetting>
                    <i nz-icon nzType="setting"></i>Setting
                </ng-template>
                <ng-template #actionDelete>
                    <i nz-icon nzType="delete"></i>Delete
                </ng-template>
            </nz-card>
          </div>

          <ng-template #actionEdit>
            <i nz-icon nzType="edit"></i>
            Edit
          </ng-template>
          <ng-template #actionDownload>
            <i nz-icon nzType="download"></i>
            Download
          </ng-template>
          <ng-template #actionSetting>
            <i nz-icon nzType="setting"></i>
            Setting
          </ng-template>
          <ng-template #actionDelete>
            <i nz-icon nzType="delete"></i>
            Delete
          </ng-template>
        </nz-card>
      </div>
    </div>
  </div>
</div>
<div *ngIf="newProject" id="projectNewDivOuter">
    <div  id="projectNewDivInner">
        <app-new-project-page (addProject)="addProject($event)"></app-new-project-page>
        <!-- <app-new-project-page (closeProjectPage)="newProject=false;"></app-new-project-page> -->
    </div>
</div>

// submarine-workbench/submarine-web/src/views/workbench/workspace/project/Index.vue
<!--
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-->
<template>
  <project-list v-if="activeTabKey === '1'" @showNewProject="onShowPage('2')"/>
  <new-project v-else-if="activeTabKey === '2'" @showProjectList="onShowPage('1')"/>
</template>

<script>
import NewProject from './NewProject'
import ProjectList from './ProjectList'

export default {
  name: 'ProjectIndex',
  components: {
    ProjectList,
    NewProject
  },
  data () {
    return {
      activeTabKey: '1'
    }
  },
  methods: {
    onShowPage (key) {
      this.activeTabKey = key
    }
  }
}
</script>
