// submarine-workbench-v2/src/App.tsx
/*!
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

import Sidebar from "@submarine/sidebar/Sidebar";
import { Navigate, Route, Routes } from "react-router-dom";
import Notebook from "@submarine/pages/workbench/notebook/Notebook";
import Experiment from "@submarine/pages/workbench/experiment/Experiment";
import Template from "@submarine/pages/workbench/template/Template";
import Environment from "@submarine/pages/workbench/environment/Environment";
import User from "@submarine/pages/workbench/user/User";
import DataDict from "@submarine/pages/workbench/data_dict/DataDict";
import Department from "@submarine/pages/workbench/department/Department";
import Model from "@submarine/pages/workbench/model/Model";
import { Layout } from "antd";

function App() {
  return (
    <Layout>
      <Sidebar></Sidebar>
      <Routes>
        <Route path="/" element={<Navigate replace to="experiment" />} />
        <Route path="notebook" element={<Notebook />} />
        <Route path="experiment" element={<Experiment />} />
        <Route path="template" element={<Template />} />
        <Route path="environment" element={<Environment />} />
        <Route path="user" element={<User />} />
        <Route path="dataDict" element={<DataDict />} />
        <Route path="department" element={<Department />} />
        <Route path="model" element={<Model />} />
      </Routes>
    </Layout>
  );
}

export default App;

// submarine-workbench/workbench-web-ng/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'submarine-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  isCollapsed = false;
}

<!--
  ~ Licensed to the Apache Software Foundation (ASF) under one
  ~ or more contributor license agreements.  See the NOTICE file
  ~ distributed with this work for additional information
  ~ regarding copyright ownership.  The ASF licenses this file
  ~ to you under the Apache License, Version 2.0 (the
  ~ "License"); you may not use this file except in compliance
  ~ with the License.  You may obtain a copy of the License at
  ~
  ~   http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing,
  ~ software distributed under the License is distributed on an
  ~ "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  ~ KIND, either express or implied.  See the License for the
  ~ specific language governing permissions and limitations
  ~ under the License.
  -->

<nz-layout class="app-layout">
  <router-outlet></router-outlet>
<!--  <nz-sider class="menu-sidebar"-->
<!--            nzCollapsible-->
<!--            nzWidth="256px"-->
<!--            nzBreakpoint="md"-->
<!--            [(nzCollapsed)]="isCollapsed"-->
<!--            [nzTrigger]="null">-->
<!--    <div class="sidebar-logo">-->
<!--      <a href="https://ng.ant.design/" target="_blank">-->
<!--        <img src="https://ng.ant.design/assets/img/logo.svg" alt="logo">-->
<!--        <h1>Ant Design Of Angular</h1>-->
<!--      </a>-->
<!--    </div>-->
<!--    <ul nz-menu nzTheme="dark" nzMode="inline" [nzInlineCollapsed]="isCollapsed">-->
<!--      <li nz-submenu nzOpen nzTitle="Dashboard" nzIcon="dashboard">-->
<!--        <ul>-->
<!--          <li nz-menu-item nzMatchRouter>-->
<!--            <a routerLink="/welcome">Welcome</a>-->
<!--          </li>-->
<!--          <li nz-menu-item nzMatchRouter>-->
<!--            <a>Monitor</a>-->
<!--          </li>-->
<!--          <li nz-menu-item nzMatchRouter>-->
<!--            <a>Workplace</a>-->
<!--          </li>-->
<!--        </ul>-->
<!--      </li>-->
<!--      <li nz-submenu nzOpen nzTitle="Form" nzIcon="form">-->
<!--        <ul>-->
<!--          <li nz-menu-item nzMatchRouter>-->
<!--            <a>Basic Form</a>-->
<!--          </li>-->
<!--        </ul>-->
<!--      </li>-->
<!--    </ul>-->
<!--  </nz-sider>-->
<!--  <nz-layout>-->
<!--    <nz-header>-->
<!--      <div class="app-header">-->
<!--        <span class="header-trigger" (click)="isCollapsed = !isCollapsed">-->
<!--            <i class="trigger"-->
<!--               nz-icon-->
<!--               [nzType]="isCollapsed ? 'menu-unfold' : 'menu-fold'"-->
<!--            ></i>-->
<!--        </span>-->
<!--      </div>-->
<!--    </nz-header>-->
<!--    <nz-content>-->
<!--      <div class="inner-content">-->
<!--        <router-outlet></router-outlet>-->
<!--      </div>-->
<!--    </nz-content>-->
<!--  </nz-layout>-->
</nz-layout>
