// submarine-workbench/workbench-web/src/app/pages/workbench/experiment/experiment.component.ts
/*!
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

import { AfterViewInit, Component, OnInit } from '@angular/core';
import { ExperimentService } from '@submarine/services/experiment.service';
import { delay } from 'rxjs/operators';

@Component({
  selector: 'submarine-experiment',
  templateUrl: './experiment.component.html',
  styleUrls: ['./experiment.component.scss'],
})
export class ExperimentComponent implements OnInit {
  experimentID: string = null;

  constructor(private experimentService: ExperimentService) {}

  ngOnInit() {
    this.experimentService.infoEmitted$.pipe(delay(0)).subscribe((id) => (this.experimentID = id));
  }
}

<!--
  ~ Licensed to the Apache Software Foundation (ASF) under one
  ~ or more contributor license agreements.  See the NOTICE file
  ~ distributed with this work for additional information
  ~ regarding copyright ownership.  The ASF licenses this file
  ~ to you under the Apache License, Version 2.0 (the
  ~ "License"); you may not use this file except in compliance
  ~ with the License.  You may obtain a copy of the License at
  ~
  ~   http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing,
  ~ software distributed under the License is distributed on an
  ~ "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  ~ KIND, either express or implied.  See the License for the
  ~ specific language governing permissions and limitations
  ~ under the License.
  -->

<nz-layout style="margin: -24px -24px 16px">
  <nz-layout>
    <div style="background-color: white; padding-left: 30px; padding-top: 20px">
      <nz-breadcrumb>
        <nz-breadcrumb-item>
          <a>Home</a>
        </nz-breadcrumb-item>
        <nz-breadcrumb-item>
          <a [routerLink]="['/', 'workbench', 'experiment']">experiment</a>
        </nz-breadcrumb-item>
        <nz-breadcrumb-item *ngIf="experimentID != null">
          {{ experimentID }}
        </nz-breadcrumb-item>
      </nz-breadcrumb>
      <div *ngIf="experimentID == null">
        <br />
        <h2>Experiment</h2>
        <nz-content>A experiment is a way of running a adhoc, pre-defined or pipeline on a scheduled basis.</nz-content>
      </div>
      <br />
    </div>
  </nz-layout>

  <router-outlet></router-outlet>
</nz-layout>

// submarine-workbench-v2/src/pages/workbench/experiment/Experiment.tsx
/*!
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

import { Layout } from "antd";

const { Content } = Layout;

function Experiment() {
  return (
    <Layout>
      <Content>Experiment</Content>
    </Layout>
  );
}
export default Experiment;
