// submarine-workbench/workbench-web/src/app/pages/workbench/model/model.component.ts
/*!
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

import { Component, OnInit } from '@angular/core';
import { ModelService } from '@submarine/services/model.service';
import { ModelVersionService } from '@submarine/services/model-version.service';
import { delay } from 'rxjs/operators';

@Component({
  selector: 'submarine-model',
  templateUrl: './model.component.html',
  styleUrls: ['./model.component.scss']
})
export class ModelComponent implements OnInit {
  modelName: string = null;
  modelVersion: string = null;

  constructor(private modelService: ModelService, private modelVersionService: ModelVersionService) {}

  ngOnInit() {
    this.modelService.infoEmitted$.pipe(delay(0)).subscribe((name) => (this.modelName = name));
    this.modelVersionService.infoEmitted$.pipe(delay(0)).subscribe((version) => this.modelVersion = version);
  }
}

<!--
  ~ Licensed to the Apache Software Foundation (ASF) under one
  ~ or more contributor license agreements.  See the NOTICE file
  ~ distributed with this work for additional information
  ~ regarding copyright ownership.  The ASF licenses this file
  ~ to you under the Apache License, Version 2.0 (the
  ~ "License"); you may not use this file except in compliance
  ~ with the License.  You may obtain a copy of the License at
  ~
  ~   http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing,
  ~ software distributed under the License is distributed on an
  ~ "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  ~ KIND, either express or implied.  See the License for the
  ~ specific language governing permissions and limitations
  ~ under the License.
  -->

<nz-layout style="margin: -24px -24px 16px">
  <div style="background-color: white; padding-left: 30px; padding-top: 20px">
    <nz-breadcrumb>
      <nz-breadcrumb-item>
        <a>Home</a>
      </nz-breadcrumb-item>
      <nz-breadcrumb-item>
        <a [routerLink]="['/', 'workbench', 'model']" (click)="modelName = null; modelVersion=null;">model</a>
      </nz-breadcrumb-item>
      <nz-breadcrumb-item *ngIf="modelName != null">
        <a [routerLink]="['/', 'workbench', 'model', modelName]" (click)="modelVersion = null;">{{ modelName }}</a>
      </nz-breadcrumb-item>
      <nz-breadcrumb-item *ngIf="modelVersion != null">
        {{ modelVersion }}
      </nz-breadcrumb-item>
    </nz-breadcrumb>
    <div *ngIf="modelName == null">
      <br />
      <h2>Model</h2>
    </div>
    <br />
  </div>
  <router-outlet></router-outlet>
</nz-layout>

// submarine-workbench-v2/src/pages/workbench/model/Model.tsx
/*!
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

import { Layout } from 'antd';

const { Content } = Layout;

function Model() {
    return (
        <Layout>
            <Content>
                Model
            </Content>
        </Layout>
    )
}
export default Model;
